<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\tyler\OneDrive\Documents\Websites\svelte\Open-Source-Government\static\models\Desk.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      ['Node-Mesh']: THREE.Mesh
      ['Node-Mesh_1']: THREE.Mesh
      ['Node-Mesh_2']: THREE.Mesh
      ['Node-Mesh_3']: THREE.Mesh
      ['Node-Mesh_4']: THREE.Mesh
      ['Node-Mesh_5']: THREE.Mesh
      ['Node-Mesh_6']: THREE.Mesh
      ['Node-Mesh_7']: THREE.Mesh
    }
    materials: {
      mat23: THREE.MeshStandardMaterial
      mat8: THREE.MeshStandardMaterial
      mat17: THREE.MeshStandardMaterial
      mat20: THREE.MeshStandardMaterial
      mat21: THREE.MeshStandardMaterial
      mat15: THREE.MeshStandardMaterial
      mat3: THREE.MeshStandardMaterial
      mat22: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Desk.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['Node-Mesh'].geometry} material={gltf.materials.mat23} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_1'].geometry} material={gltf.materials.mat8} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_2'].geometry} material={gltf.materials.mat17} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_3'].geometry} material={gltf.materials.mat20} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_4'].geometry} material={gltf.materials.mat21} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_5'].geometry} material={gltf.materials.mat15} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_6'].geometry} material={gltf.materials.mat3} />
    <T.Mesh geometry={gltf.nodes['Node-Mesh_7'].geometry} material={gltf.materials.mat22} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
