<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\tyler\OneDrive\Documents\Websites\svelte\Open-Source-Government\static\models\voting_machine.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      ['Voting_machine_Cube028-Mesh']: THREE.Mesh
      ['Voting_machine_Cube028-Mesh_1']: THREE.Mesh
      ['Voting_machine_Cube028-Mesh_2']: THREE.Mesh
      ['Voting_machine_Cube028-Mesh_3']: THREE.Mesh
      ['Voting_machine_Cube028-Mesh_4']: THREE.Mesh
    }
    materials: {
      FFFFFF: THREE.MeshStandardMaterial
      ['455A64']: THREE.MeshStandardMaterial
      ['1A1A1A']: THREE.MeshStandardMaterial
      F44336: THREE.MeshStandardMaterial
      ['039BE5']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/voting_machine.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['Voting_machine_Cube028-Mesh'].geometry} material={gltf.materials.FFFFFF} />
    <T.Mesh geometry={gltf.nodes['Voting_machine_Cube028-Mesh_1'].geometry} material={gltf.materials['455A64']} />
    <T.Mesh geometry={gltf.nodes['Voting_machine_Cube028-Mesh_2'].geometry} material={gltf.materials['1A1A1A']} />
    <T.Mesh geometry={gltf.nodes['Voting_machine_Cube028-Mesh_3'].geometry} material={gltf.materials.F44336} />
    <T.Mesh geometry={gltf.nodes['Voting_machine_Cube028-Mesh_4'].geometry} material={gltf.materials['039BE5']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
